---
title: "Economic and Health Effects of Weather Events"
author: "Thomas Barrett"
date: "December 24, 2018"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

## Synopsis

## Data Processing
```{r libraries}
library(R.utils)
library(data.table)
library(stringdist)
library(dplyr)
library(plyr)
library(lubridate)

```

```{r reading the data, cache=TRUE}
remote_file <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
local_file <- "rawdata.csv.bz2"
unzipped_file <- "rawdata.csv"

wd <- getwd()
print(paste("Your working directory is set to", wd))

download.file(remote_file, local_file)
bunzip2(local_file, unzipped_file, skip = TRUE, remove = FALSE)
df <- fread(unzipped_file)
head(df)
```

```{r data processing, cache=TRUE}

cutoff <- ymd_hms("1996 Jan 01 0:00:00")
df2 <- df %>% mutate(date = mdy_hms(BGN_DATE)) %>% filter(date >= cutoff) %>% 
        select(date, event_type = EVTYPE, fatalities = FATALITIES, injuries = INJURIES, prop_dmg_val = PROPDMG, prop_dmg_exp = PROPDMGEXP, crop_dmg_val = CROPDMG, crop_dmg_exp = CROPDMGEXP)
head(df2)

exp_p <- df2$prop_dmg_exp
exp_c <- df2$crop_dmg_exp

mult_p <- integer(length(exp_p))
mult_c <- integer(length(exp_c))

mult_p[which(exp_p == "")] <- 0
mult_p[which(exp_p == "0")] <- 10
mult_p[which(exp_p == "K")] <- 10^3
mult_p[which(exp_p == "M")] <- 10^6
mult_p[which(exp_p == "B")] <- 10^9

mult_c[which(exp_c == "")] <- 0
mult_c[which(exp_c == "0")] <- 10
mult_c[which(exp_c == "K")] <- 10^3
mult_c[which(exp_c == "M")] <- 10^6
mult_c[which(exp_c == "B")] <- 10^9

df3 <- df2 %>% mutate(event_type = tolower(event_type), prop_dmg = prop_dmg_val*mult_p,
                      crop_dmg = crop_dmg_val*mult_c) %>%
        select(date, event_type, fatalities, injuries, prop_dmg, crop_dmg)
head(df3)


rough_types <- unique(df3$event_type)
summaries <- rough_types[grep(pattern = "summary", rough_types)]

df4 <- df3 %>% filter(!(event_type %in% summaries))

types <- c("astronomical low tide","avalanche","blizzard","coastal flood","cold/wind chill",
           "debris flow","dense fog","dense smoke","drought","dust devil","dust storm",
           "excessive heat","extreme cold/wind chill","flash flood","flood","frost/freeze",
           "funnel cloud","freezing fog","hail","heat","heavy rain","heavy snow","high surf",
           "high wind","hurricane (typhoon)","ice storm","lake-effect snow","lakeshore flood",
           "lightning","marine hail","marine high wind","marine strong wind","marine thunderstorm wind",
           "rip current","seiche","sleet","storm surge/tide","strong wind","thunderstorm wind",
           "tornado","tropical depression","tropical storm","tsunami","volcanic ash",
           "waterspout","wildfire","winter storm","winter weather")

positions <- amatch(df4$event_type, types, maxDist = 0.1, method = "jw")
replacements <- types[positions]
df4$event_type[!is.na(replacements)] <- replacements[!is.na(replacements)]

uniq_types <- unique(df4$event_type)



#######################
## Use mapvalues function from plyr package!
#######################


###################
## REMOVE ME NEXT SESSION
###################

## positions <- amatch(uniq_types, types, maxDist = 0.1, method = "jw")
## temp_matrix <- cbind(uniq_types, types[positions])
## compare <- as.data.frame(temp_matrix)
## head(compare, n = 10)

###################
###################

```

## Results

```{r results}

```
